#!/usr/bin/python
"""
Runs the 4 exes
"""

import argparse
from pypfant import *
import matplotlib.pyplot as plt

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )

    parser.add_argument('fn', type=str, nargs='+',
                        help='name of spertrum file (either generated by pfant or nulbad)')

    args = parser.parse_args()

    ss = []
    for x in args.fn:

        print "Trying to read file '%s'..." % x
        # tries to load as pfant ouput; if fails, tries as nulbad output
        try:
            f = FileSpectrumPfant()
            f.load(x)
            print "... file is pfant output"
        except:
            f = FileSpectrumNulbad()
            f.load(x)
            print "... file is nulbad output"

        ss.append(f.spectrum)
    plot_spectra(ss)
    plt.show()