var namespaces =
[
    [ "absoru", "namespaceabsoru.html", null ],
    [ "absoru_data", "namespaceabsoru__data.html", null ],
    [ "ascii_canvas", "namespaceascii__canvas.html", null ],
    [ "config", "namespaceconfig.html", null ],
    [ "dimensions", "namespacedimensions.html", null ],
    [ "flin", "namespaceflin.html", null ],
    [ "hydro2_calc", "namespacehydro2__calc.html", null ],
    [ "hydro2_math", "namespacehydro2__math.html", null ],
    [ "hydro2_x", "namespacehydro2__x.html", null ],
    [ "innewmarcs_calc", "namespaceinnewmarcs__calc.html", null ],
    [ "innewmarcs_x", "namespaceinnewmarcs__x.html", null ],
    [ "logging", "namespacelogging.html", null ],
    [ "misc", "namespacemisc.html", null ],
    [ "misc_math", "namespacemisc__math.html", null ],
    [ "molecules_idxs", "namespacemolecules__idxs.html", null ],
    [ "nulbad_calc", "namespacenulbad__calc.html", null ],
    [ "options2", "namespaceoptions2.html", null ],
    [ "qsort", "namespaceqsort.html", null ],
    [ "reader_abonds", "namespacereader__abonds.html", null ],
    [ "reader_absoru2", "namespacereader__absoru2.html", null ],
    [ "reader_atoms", "namespacereader__atoms.html", null ],
    [ "reader_dissoc", "namespacereader__dissoc.html", null ],
    [ "reader_gridsmap", "namespacereader__gridsmap.html", null ],
    [ "reader_main", "namespacereader__main.html", null ],
    [ "reader_modeles", "namespacereader__modeles.html", null ],
    [ "reader_molecules", "namespacereader__molecules.html", null ],
    [ "reader_partit", "namespacereader__partit.html", null ],
    [ "readers", "namespacereaders.html", null ],
    [ "welcome", "namespacewelcome.html", null ]
];